### ISSUE TITLE
Code doesn't work for latest version of the API

### ISSUE THREAD

**Issue by samvher** [netogallo/Microsoft-Translator-Haskell#2]
Some things have changed now that they made the translator API part of Azure, in particular the way you get a token (there is a different address now, and you use a single key instead of id + secret). I adapted your code, also made some stylistic changes, you can find my changed version here:
https://github.com/samvher/translatethenews/blob/master/src/Language/Bing.hs

(I'm not making a pull request because it might be too many changes at once, and for people with an old account with Microsoft the old procedure might still work.)

**Comment by netogallo** [comment]
Great! Thanks. I am no longer mantaining the project because I am not using it anymore. If you want to become the hackage owner, let me know.
